apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: vault
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: kube-system
      interval: 12h