apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook
  namespace: rook-ceph
spec:
  interval: 24h
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: rook-ceph
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: rook-ceph
      interval: 12h