apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
namespace: kube-system
metadata:
  name: foo
spec:
  parentRefs:
  - name: prod-web
  rules:
  - backendRefs:
    - name: vault-ui
      port: 8200