apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth 
  namespace: clonedameshi
spec:
  method: kubernetes 
  mount: kubernetes
  kubernetes:
      role: clonedameshi 
      serviceAccount: default 

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret 
metadata: 
  namespace: clonedameshi 
  name: vault-static-secret-clonedameshi 
spec: 
  vaultAuthRef: static-auth 
  mount: kv-v2 
  type: kv-v2 
  path: clonedameshi/secret 
  refreshAfter: 10s
  # rolloutRestartTargets:
  # - kind: Deployment
  #  name: clonedameshi
  destination: 
    create: true
    name: secret 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clonedameshi
  name: clonedameshi
  namespace: clonedameshi
spec:
  selector:
    matchLabels:
      app: clonedameshi 
  template: 
    metadata:
      labels:
        app: clonedameshi 
    spec: 
      containers:
        - image: nginx
          name: nginx 
          env: 
          - name: DISCORD_TOKEN 
            valueFrom: 
              secretKeyRef:
                name: clonedameshi 
                key: DISCORD_TOKEN 
          - name: TEST_GUILD_ID 
            valueFrom: 
              secretKeyRef:
                name: clonedameshi 
                key: TEST_GUILD_ID 
          - name: SUBMISSIONS_CHANNEL_NAME 
            valueFrom: 
              secretKeyRef:
                name: clonedameshi 
                key: SUBMISSIONS_CHANNEL_NAME 
          resources: {}